version: '3.8'

services:
  chatapp:
    build:
      context: .
      dockerfile: ChatApp/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - chatserver

  chatserver:
    build:
      context: .
      dockerfile: ChatServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development